In [1]:
import av

from PIL import Image
from matplotlib import pyplot as plt

import tensorflow as tf

import keras
from keras import layers
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense, BatchNormalization, Dropout, Layer
from keras.optimizers import Adam
from keras import backend as K

import os
import random
import math
import numpy as np
import cv2

In [2]:
DS_CDFV1 = 'celeb_df_v1/'
DS_CDFV2 = 'celeb_df_v2/'

DS_ORGINAL = 'dataset_original/'
DS_SPLIT = 'dataset_split/'
DS_IFRAMES = 'dataset_iframes/'
DS_FACE = 'dataset_face/'
DS_FACE_IMG = 'dataset_face_img/'
DS_SRM_SNIPPETS = 'dataset_srm_snippets_5/'
DS_SEGMENTS = 'dataset_segments/'
DS_RAW = 'dataset_raw/'
DS_RESIDUALS = 'dataset_residuals/'

SEG_1 = 'seg_1/'
SEG_2 = 'seg_2/'
SEG_3 = 'seg_3/'
SEG_4 = 'seg_4/'
SEG_5 = 'seg_5/'

DS_TRAIN = 'train_dataset/'
DS_TEST = 'test_dataset/'
DS_VAL = 'val_dataset/'

CLASS_FAKE = 'fake/'
CLASS_REAL = 'real/'


TOP_LEVEL_1 = [DS_SPLIT, DS_IFRAMES, DS_FACE, DS_FACE_IMG, DS_SRM_SNIPPETS]
TOP_LEVEL_2 = [DS_SEGMENTS, DS_RAW, DS_RESIDUALS]
SEGMENTS = [SEG_1, SEG_2, SEG_3, SEG_4, SEG_5]
SPLIT = [DS_TRAIN, DS_TEST, DS_VAL]
CLASS = [CLASS_REAL, CLASS_FAKE]

DATASET = [DS_CDFV1, DS_CDFV2]

# Snippet Extraction

## Functions

In [100]:
# Returns the index of frames that begin a new segment (except the first segment)
def get_segment_dividers(frame_count, num_segments):
    segments_per_frame = math.floor(frame_count / num_segments)

    return [(segments_per_frame * i) for i in range(1, num_segments) ]

In [101]:
# Returns the indices of the frames that will be randomly selected from each segment
# Multiple snippets indices per segment can be returned by setting the num_snippets arg 
def get_snippet_indices(segment_dividers, num_snippets):
    start_index = 0
    num_snippets = 1 if num_snippets <= 0 else num_snippets

    snippet_indices = []
    for end_index in segment_dividers:

        # Extracting multiple snippets per segment (if needed)
        for _ in range(num_snippets):
            snippet_indices.append(random.randint(start_index, end_index - 1))

        start_index = end_index
        
    return snippet_indices

In [102]:
# Returns an array of randomly selected snippets(PIL.Image) from each segment of the input video
def extract_snippets(fp, num_segments, num_snippets):
    vid_container = av.open(fp)
    vid_stream = vid_container.streams.video[0]
    frame_count = vid_stream.frames

    snippets = []

    # If number of frames in video is less than the number of frames that need to sampled
    # then take all frames in the video
    if frame_count < num_segments * num_snippets:
        for frame in vid_container.decode():
            snippets.append(frame.to_image())

    else:
        segment_dividers = get_segment_dividers(frame_count, num_segments)
        segment_dividers = segment_dividers + [frame_count]

        snippet_indices = get_snippet_indices(segment_dividers, num_snippets)

        frame_index = 0
        for frame in vid_container.decode():
            if frame_index > max(snippet_indices):
                break

            if frame_index in snippet_indices:
                snippets.append(frame.to_image())

            frame_index += 1

    return snippets

## Testing Logic

In [54]:
tmp_count = 30
tmp_seg = get_segment_dividers(tmp_count, 3)
tmp_snip = get_snippet_indices(tmp_seg + [tmp_count], 2)

print(f'Segment Dividers: {tmp_seg}')
print(f'Snippets{tmp_snip}')

Segment Dividers: [10, 20]
Snippets[4, 9, 15, 13, 20, 26]


In [99]:
# test_file = os.listdir(DS_CDFV1 + DS_SPLIT + DS_TRAIN + CLASS_REAL)[0]
test_file = DS_CDFV2 + DS_SPLIT + DS_TRAIN + CLASS_REAL + 'id27_0005.mp4'
# test_input = av.open(os.path.realpath(DS_CDFV1 + DS_SPLIT + DS_TRAIN + CLASS_REAL + test_file))
test_input = av.open(test_file)

print(test_input.streams.video[0].frames)

# for frame in test_input.decode():
#     print(frame.key_frame)

1


In [95]:
# test_file = os.listdir(DS_CDFV1 + DS_FACE + DS_TRAIN + CLASS_REAL)[0]
test_file = DS_CDFV2 + DS_FACE + DS_TRAIN + CLASS_REAL + 'id27_0005.mp4'
# test_file = DS_CDFV1 + DS_FACE + DS_TRAIN + CLASS_REAL + test_file
tmp_snippets = extract_snippets(test_file, 5, 1)

for s in tmp_snippets:
    s.show()

## Implementation

### Celeb-DF v1 & v2

In [103]:
def save_snippets_CDF(dataset, num_segments, num_snippets):
    if dataset != DS_CDFV1 and dataset != DS_CDFV2:
        print(dataset)
        return
    
    random.seed(1)
    
    src_base_path = dataset + DS_FACE
    dst_base_path = dataset + DS_SRM_SNIPPETS

    for split in SPLIT:
        print(f'---Split started: {split}---')
        for class_dir in CLASS:
            print(f'Class started: {class_dir}')

            for video in os.listdir(src_base_path + split + class_dir):
                fp = src_base_path + split + class_dir + video
                snippets = extract_snippets(fp, num_segments, num_snippets)

                for i, snippet in enumerate(snippets, start=1):
                    seg_index = math.ceil(float(i) / num_snippets)
                    snip_index = (i - 1) % num_snippets
              
                    dst = f'{dst_base_path + split + class_dir + os.path.splitext(video)[0]}_s{seg_index}_f{snip_index}.jpeg'
                    snippet.save(dst)         

In [85]:
# CELEB DF V1
save_snippets_CDF(DS_CDFV1, num_segments=5, num_snippets=1)

---Split started: train_dataset/---
Class started: real/
Class started: fake/
---Split started: test_dataset/---
Class started: real/
Class started: fake/
---Split started: val_dataset/---
Class started: real/
Class started: fake/


In [104]:
# CELEB DF V2
save_snippets_CDF(DS_CDFV2, num_segments=5, num_snippets=1)

---Split started: train_dataset/---
Class started: real/
Class started: fake/
---Split started: test_dataset/---
Class started: real/
Class started: fake/
---Split started: val_dataset/---
Class started: real/
Class started: fake/


# Tensor Dataset Creation

In [15]:
def create_tensor_dataset(dataset, split):
    ds = keras.utils.image_dataset_from_directory(
        directory = dataset + DS_SRM_SNIPPETS + split,
        labels = 'inferred',
        label_mode = 'binary',
        batch_size = 32,
        color_mode = 'rgb',
        shuffle = True,
        seed = 1
    )

    return ds

## Celeb DF v1

In [16]:
train_dataset_cdfv1 = create_tensor_dataset(DS_CDFV1, DS_TRAIN)
test_dataset_cdfv1 = create_tensor_dataset(DS_CDFV1, DS_TEST)
val_dataset_cdfv1 = create_tensor_dataset(DS_CDFV1, DS_VAL)

Found 4415 files belonging to 2 classes.
Found 500 files belonging to 2 classes.
Found 1100 files belonging to 2 classes.


## Celeb DF v2

In [39]:
train_dataset_cdfv2 = create_tensor_dataset(DS_CDFV2, DS_TRAIN)
test_dataset_cdfv2 = create_tensor_dataset(DS_CDFV2, DS_TEST)
val_dataset_cdfv2 = create_tensor_dataset(DS_CDFV2, DS_VAL)

Found 24046 files belonging to 2 classes.
Found 2590 files belonging to 2 classes.
Found 6005 files belonging to 2 classes.


# Model Creation

## Functions

In [32]:
class SRMLayer(Layer):
    def __init__(self, filters, kernel_size, fixed_filters, **kwargs):
        super(SRMLayer, self).__init__(**kwargs)
        self.filters = filters
        self.kernel_size = kernel_size
        self.fixed_filters = fixed_filters

        self.q_small = self.add_weight(name='q_small',
                                       shape=(),
                                       initializer=keras.initializers.Constant(value=2.0),
                                       trainable=True)
        
        self.q_med = self.add_weight(name='q_med',
                                     shape=(),
                                     initializer=keras.initializers.Constant(value=4.0),
                                     trainable=True)
        
        self.q_large = self.add_weight(name='q_large',
                                       shape=(),
                                       initializer=keras.initializers.Constant(value=12.0),
                                       trainable=True)
        
        def build(self, input_shape):
            super(SRMLayer, self).build(input_shape)
            fixed_filters = tf.constant(self.fixed_filters, dtype=tf.float32)
            print(fixed_filters)

        def call(self, inputs):
            fixed_filters = tf.constant(self.fixed_filters, dtype=tf.float32)

            # print(fixed_filters[:, :, 0:1, :])

            output1 = tf.nn.conv2d(inputs, fixed_filters[:, :, 0:1, :], strides=[1, 1, 1, 1], padding='SAME')
            output2 = tf.nn.conv2d(inputs, fixed_filters[:, :, 1:2, :], strides=[1, 1, 1, 1], padding='SAME')
            output3 = tf.nn.conv2d(inputs, fixed_filters[:, :, 2:3, :], strides=[1, 1, 1, 1], padding='SAME')

            output1 /= self.q_small
            output2 /= self.q_med
            output3 /= self.q_large

            output = tf.concat([output1, output2, output3], axis=3)
            return output
        
        def compute_output_shape(self, input_shape):
            batch_size = input_shape[0]
            height = input_shape[1]
            width = input_shape[2]

        def get_config(self):
            config = super(SRMLayer, self).get_config()
            config.update({'filters': self.filters,
                           'kernel_size': self.kernel_size,
                           'fixed_filters': self.fixed_filters})
            
            return config


## Testing Logic

**For Convolution**
- Input Shape:  [batch_size, height, width, channels]
- Filter Shape: [height, width, in_channels, filter_count]

In [4]:
tmp_filter_small = tf.constant([[0, 0,  0, 0, 0],
                                [0, 0,  0, 0, 0],
                                [0, 1, -2, 1, 0],
                                [0, 0,  0, 0, 0],
                                [0, 0,  0, 0, 0]], dtype=tf.float32)

tmp_filter_med = tf.constant([[0,  0,  0,  0, 0],
                              [0, -1,  2, -1, 0],
                              [0,  2, -4,  2, 0],
                              [0, -1,  2, -1, 0],
                              [0,  0,  0,  0, 0]], dtype=tf.float32)

tmp_filter_small = tf.expand_dims(tf.expand_dims(tmp_filter_small, axis=-1), axis=-1)
tmp_filter_med   = tf.expand_dims(tf.expand_dims(tmp_filter_med,   axis=-1), axis=-1)
# tf.print(tmp_filter_small.shape)

tmp_filter_small = tf.tile(tmp_filter_small, [1, 1, 3, 1])
tmp_filter_med   = tf.tile(tmp_filter_med,   [1, 1, 3, 1])

tmp_filters = tf.concat([tmp_filter_small, tmp_filter_med], axis=3)

tf.print(tmp_filters.shape)

tmp_conv = Conv2D(filters=2, 
                  kernel_size=5, 
                  kernel_initializer=tf.keras.initializers.Constant(tmp_filters))

tmp_x = tf.random.normal([32, 256, 256, 3])
tmp_y = tmp_conv(tmp_x)

print(tmp_y.shape)

TensorShape([5, 5, 3, 2])
(32, 252, 252, 2)


In [27]:
tmp_filter_small = tf.constant([[0, 0,  0, 0, 0],
                                [0, 0,  0, 0, 0],
                                [0, 1, -2, 1, 0],
                                [0, 0,  0, 0, 0],
                                [0, 0,  0, 0, 0]], dtype=tf.float32)

tmp_q = tf.constant([0], dtype=tf.float32)
tmp_nz = tf.constant([0.1], dtype=tf.float32)

tmp_q  = tf.expand_dims(tmp_q,  axis=-1)
tmp_nz = tf.expand_dims(tmp_nz, axis=-1)

tmp_q  = tf.tile(tmp_q, [5, 5])
tmp_nz = tf.tile(tmp_nz, [5, 5])

print(tmp_q)
tmp_q = tf.where(tf.equal(tmp_q, 0), tmp_nz, tmp_q)
print(tmp_q)


tmp_filter_small = tf.math.divide(tmp_filter_small, tmp_q)

print(tmp_filter_small)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.  10. -20.  10.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]], shape=(5, 5), dtype=float32)


In [5]:
tmp_x = tf.constant([[0, 0,  0, 0, 0],
                                [0, 0,  0, 0, 0],
                                [0, 1, -2, 1, 0],
                                [0, 0,  0, 0, 0],
                                [0, 0,  0, 0, 0]])
tmp_y = tf.constant([2])

tmp_res = tf.divide(tmp_x, tmp_y)

print(tmp_x)
print(tmp_y)
print(tmp_res)

tf.Tensor(
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  1 -2  1  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]], shape=(5, 5), dtype=int32)
tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor(
[[ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.5 -1.   0.5  0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]], shape=(5, 5), dtype=float64)


### Custom SRM Layer

In [9]:
class SSRM(Layer):
    def __init__(self, **kwargs):
        super(SSRM, self).__init__(**kwargs)

        self.filter_small = tf.constant([[0, 0,  0, 0, 0],
                                         [0, 0,  0, 0, 0],
                                         [0, 1, -2, 1, 0],
                                         [0, 0,  0, 0, 0],
                                         [0, 0,  0, 0, 0]], dtype=tf.float32)
        
        self.filter_med = tf.constant([[0,  0,  0,  0, 0],
                                       [0, -1,  2, -1, 0],
                                       [0,  2, -4,  2, 0],
                                       [0, -1,  2, -1, 0],
                                       [0,  0,  0,  0, 0]], dtype=tf.float32)
        
        self.filter_large = tf.constant([[-1,  2,  -2,  2, -1],
                                         [ 2, -6,   8, -6,  2],
                                         [-2,  8, -12,  8, -2],
                                         [ 2, -6,   8, -6,  2],
                                         [-1,  2,  -2,  2, -1]], dtype=tf.float32)
        
        self.filter_small = tf.expand_dims(tf.expand_dims(self.filter_small, axis=-1), axis=-1)
        self.filter_med   = tf.expand_dims(tf.expand_dims(self.filter_med,   axis=-1), axis=-1)
        self.filter_large = tf.expand_dims(tf.expand_dims(self.filter_large, axis=-1), axis=-1)

        self.filter_small = tf.tile(self.filter_small, [1, 1, 3, 1])
        self.filter_med   = tf.tile(self.filter_med,   [1, 1, 3, 1])
        self.filter_large = tf.tile(self.filter_large, [1, 1, 3, 1])
        
        def call(self, inputs):
            output_small = tf.nn.conv2d(inputs, self.filter_small, strides=[1, 1, 1, 1], padding='SAME')
            output_med   = tf.nn.conv2d(inputs, self.filter_med,   strides=[1, 1, 1, 1], padding='SAME')
            output_large = tf.nn.conv2d(inputs, self.filter_large, strides=[1, 1, 1, 1], padding='SAME')

            return tf.concat([output_small, output_med, output_large], axis=3)

In [ ]:
class PSRM(Layer):
    def __init__(self, **kwargs):
        super(PSRM, self).__init__(**kwargs)

        self.filter_small = tf.constant([[0, 0,  0, 0, 0],
                                         [0, 0,  0, 0, 0],
                                         [0, 1, -2, 1, 0],
                                         [0, 0,  0, 0, 0],
                                         [0, 0,  0, 0, 0]], dtype=tf.float32)
        
        self.filter_small = tf.expand_dims(tf.expand_dims(self.filter_small, axis=-1), axis=-1)
        self.filter_small = tf.tile(self.filter_small, [1, 1, 3, 1])

        self.q_small = self.add_weight(name = 'q_small',
                                       shape = (1, ), 
                                       initializer = tf.initializers.Constant(value=2.0),
                                       trainable = True)
        
        def call(self, inputs):
            filter_small = tf.math.divide(self.filter_small, self.q_small)
            output_small = tf.nn.conv2d(inputs, filter_small, strides=[1, 1, 1, 1], padding='SAME')

            return output_small

In [31]:
class PSRM_3(Layer):
    def __init__(self, **kwargs):
        super(PSRM_3, self).__init__(**kwargs)

        self.filter_small = tf.constant([[0, 0,  0, 0, 0],
                                         [0, 0,  0, 0, 0],
                                         [0, 1, -2, 1, 0],
                                         [0, 0,  0, 0, 0],
                                         [0, 0,  0, 0, 0]], dtype=tf.float32)
        
        # self.filter_med = tf.constant([[0,  0,  0,  0, 0],
        #                                [0, -1,  2, -1, 0],
        #                                [0,  2, -4,  2, 0],
        #                                [0, -1,  2, -1, 0],
        #                                [0,  0,  0,  0, 0]], dtype=tf.float32)
        
        # self.filter_large = tf.constant([[-1,  2,  -2,  2, -1],
        #                                  [ 2, -6,   8, -6,  2],
        #                                  [-2,  8, -12,  8, -2],
        #                                  [ 2, -6,   8, -6,  2],
        #                                  [-1,  2,  -2,  2, -1]], dtype=tf.float32)
        
        self.q_small = self.add_weight(name = 'q_small',
                                       shape = (1, ), 
                                       initializer = tf.initializers.Constant(value=2.0),
                                       trainable = True)
        
        # self.q_med = self.add_weight(name = 'q_med', 
        #                              shape = (1, ),
        #                              initializer = tf.initializers.Constant(value=4.0),
        #                              trainable = True)
        
        # self.q_large = self.add_weight(name = 'q_large', 
        #                                shape = (1, ),
        #                                initializer = tf.initializers.Constant(value=12.0),
        #                                trainable = True)
        
        self.filter_small = tf.expand_dims(tf.expand_dims(self.filter_small, axis=-1), axis=-1)
        # self.filter_med   = tf.expand_dims(tf.expand_dims(self.filter_med,   axis=-1), axis=-1)
        # self.filter_large = tf.expand_dims(tf.expand_dims(self.filter_large, axis=-1), axis=-1)

        self.filter_small = tf.tile(self.filter_small, [1, 1, 3, 1])
        # self.filter_med   = tf.tile(self.filter_med,   [1, 1, 3, 1])
        # self.filter_large = tf.tile(self.filter_large, [1, 1, 3, 1])

        def call(self, inputs):
            filter_small = tf.math.divide(self.filter_small, self.q_small)
            # filter_med   = tf.divide(self.filter_med, self.q_med)
            # filter_large = tf.divide(self.filter_large, self.q_large)

            output_small = tf.nn.conv2d(inputs, filter_small, strides=[1, 1, 1, 1], padding='SAME')
            # output_med   = tf.nn.conv2d(inputs, filter_med,   strides=[1, 1, 1, 1], padding='SAME')
            # output_large = tf.nn.conv2d(inputs, filter_large, strides=[1, 1, 1, 1], padding='SAME')

            return output_small
            # return tf.concat([output_small, output_med, output_large], axis=3)

In [32]:
tmp_model = keras.Sequential([
    keras.layers.Input(shape=(256, 256, 3)),
    PSRM(),
    Flatten(),
    Dense(1, activation='sigmoid')
])

tmp_model.compile(optimizer = keras.optimizers.Adam(),
                  loss = keras.losses.BinaryCrossentropy(),
                  metrics = ['accuracy'])

tmp_model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 psrm_4 (PSRM)               (None, 256, 256, 3)       1         
                                                                 
 flatten_6 (Flatten)         (None, 196608)            0         
                                                                 
 dense_4 (Dense)             (None, 1)                 196609    
                                                                 
Total params: 196,610
Trainable params: 196,610
Non-trainable params: 0
_________________________________________________________________


In [33]:
tmp_history = tmp_model.fit(train_dataset_cdfv1, epochs=1, validation_data=val_dataset_cdfv1)

138/138 [==============================] - 7s 45ms/step - loss: 1453.7006 - accuracy: 0.5764 - val_loss: 596.7103 - val_accuracy: 0.4455


### Checking Custom Dense Layer

In [10]:
class TMPDense(keras.layers.Layer):
    def __init__(self, units, input_dim):
        super(TMPDense, self).__init__()

        self.w = self.add_weight(name = 'w',
                                 shape = (input_dim, units),
                                 initializer = tf.initializers.random_normal,
                                 trainable = True)
        
        self.b = self.add_weight(name = 'b',
                                  shape = (units, ),
                                  initializer = tf._initializers.zeros,
                                  trainable = True)
        
        self.m = self.add_weight(name = 'm',
                                 shape = (1, ),
                                 initializer = tf.initializers.Constant(value=2.0),
                                 trainable=True)
        
    def call(self, inputs):
        div = tf.math.divide(self.w, self.m)
        return tf.matmul(inputs, div) + self.b

In [12]:
dModel = keras.Sequential([
    keras.layers.Input(shape=(256,256,3)),
    SSRM(),
    Flatten(),
    TMPDense(5, 196608),
    TMPDense(1, 5),
])

dModel.compile(optimizer = keras.optimizers.Adam(),
               loss = keras.losses.BinaryCrossentropy(),
               metrics = ['accuracy']
               )

dModel.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 ssrm_1 (SSRM)               (None, 256, 256, 3)       0         
                                                                 
 flatten_1 (Flatten)         (None, 196608)            0         
                                                                 
 tmp_dense_2 (TMPDense)      (None, 5)                 983046    
                                                                 
 tmp_dense_3 (TMPDense)      (None, 1)                 7         
                                                                 
Total params: 983,053
Trainable params: 983,053
Non-trainable params: 0
_________________________________________________________________


In [13]:
dModel.layers[3].get_weights()

[array([[-0.00287271],
        [-0.04635007],
        [ 0.03803451],
        [-0.02399216],
        [-0.03421838]], dtype=float32),
 array([0.], dtype=float32),
 array([2.], dtype=float32)]

In [17]:
dModel.fit(train_dataset_cdfv1, epochs=5, validation_data=val_dataset_cdfv1)

Epoch 1/5
138/138 [==============================] - 23s 131ms/step - loss: 5.1639 - accuracy: 0.6650 - val_loss: 5.1884 - val_accuracy: 0.6636
Epoch 2/5
138/138 [==============================] - 10s 69ms/step - loss: 5.1708 - accuracy: 0.6648 - val_loss: 5.1884 - val_accuracy: 0.6636
Epoch 3/5
138/138 [==============================] - 16s 113ms/step - loss: 5.1708 - accuracy: 0.6648 - val_loss: 5.1884 - val_accuracy: 0.6636
Epoch 4/5
138/138 [==============================] - 12s 82ms/step - loss: 5.1708 - accuracy: 0.6648 - val_loss: 5.1884 - val_accuracy: 0.6636
Epoch 5/5
138/138 [==============================] - 11s 76ms/step - loss: 5.1708 - accuracy: 0.6648 - val_loss: 5.1884 - val_accuracy: 0.6636


In [18]:
dModel.layers[3].get_weights()

[array([[-0.01285018],
        [-0.05632751],
        [ 0.04801176],
        [-0.01401469],
        [-0.0242409 ]], dtype=float32),
 array([-0.00997706], dtype=float32),
 array([2.0099752], dtype=float32)]

### Custom Conv2D Layer

In [41]:
class TMPConv(Layer):
    def __init__(self):
        super(TMPConv, self).__init__()

        self.kernel = self.add_weight(name = 'kernel', 
                                      shape = (3, 3, 3, 1),
                                      initializer = tf.initializers.random_normal,
                                      trainable = True)
        
        
    def call(self, inputs):
        return tf.nn.conv2d(inputs, self.kernel, strides = [1,1,1,1], padding='SAME')

In [42]:
tmp_model = keras.Sequential([
    keras.layers.Input(shape=(256, 256, 3)),
    TMPConv(),
    Flatten(),
    Dense(1, activation='sigmoid'),
])

tmp_model.compile(loss=keras.losses.BinaryCrossentropy(),
                  optimizer=Adam(),
                  metrics=['acc'])

tmp_model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 tmp_conv_2 (TMPConv)        (None, 256, 256, 1)       27        
                                                                 
 flatten_9 (Flatten)         (None, 65536)             0         
                                                                 
 dense_7 (Dense)             (None, 1)                 65537     
                                                                 
Total params: 65,564
Trainable params: 65,564
Non-trainable params: 0
_________________________________________________________________


In [43]:
tmp_model.layers[0].get_weights()

[array([[[[ 0.01082886],
          [ 0.0721704 ],
          [ 0.06314751]],
 
         [[ 0.00422159],
          [ 0.06482067],
          [-0.12442797]],
 
         [[ 0.01848338],
          [ 0.00169939],
          [-0.09155348]]],
 
 
        [[[ 0.00671694],
          [-0.01156982],
          [ 0.05192506]],
 
         [[-0.01723207],
          [-0.00908884],
          [ 0.04879386]],
 
         [[-0.06806997],
          [ 0.01221262],
          [ 0.01048027]]],
 
 
        [[[ 0.03121798],
          [-0.09013098],
          [-0.02875078]],
 
         [[-0.02750469],
          [ 0.04947739],
          [-0.03677714]],
 
         [[-0.0318876 ],
          [ 0.02067011],
          [ 0.07242   ]]]], dtype=float32)]

In [44]:
tmp_model.fit(train_dataset_cdfv1, epochs=1, validation_data=val_dataset_cdfv1)

138/138 [==============================] - 29s 203ms/step - loss: 6.1918 - acc: 0.6027 - val_loss: 1.0617 - val_acc: 0.6336


In [45]:
tmp_model.layers[0].get_weights()

[array([[[[ 0.01429241],
          [ 0.07048156],
          [ 0.06183848]],
 
         [[ 0.0079709 ],
          [ 0.06347314],
          [-0.12531525]],
 
         [[ 0.02252773],
          [ 0.00068383],
          [-0.09209473]]],
 
 
        [[[ 0.01043839],
          [-0.01300415],
          [ 0.05080117]],
 
         [[-0.01322258],
          [-0.01017844],
          [ 0.04809758]],
 
         [[-0.0637646 ],
          [ 0.01145741],
          [ 0.01013192]]],
 
 
        [[[ 0.0351655 ],
          [-0.09134953],
          [-0.02964653]],
 
         [[-0.02326937],
          [ 0.04860467],
          [-0.03724435]],
 
         [[-0.02735478],
          [ 0.02013623],
          [ 0.0723052 ]]]], dtype=float32)]

### Old

In [15]:
class TSRM(Layer):
    def __init__(self, **kwargs):
        super(TSRM, self).__init__(**kwargs)

        self.filter_small = tf.constant([[0, 0,  0, 0, 0],
                                         [0, 0,  0, 0, 0],
                                         [0, 1, -2, 1, 0],
                                         [0, 0,  0, 0, 0],
                                         [0, 0,  0, 0, 0]], dtype=tf.float32)
        
        self.q_small = self.add_weight(shape=(),
                                       initializer='ones',
                                       dtype=tf.float32,
                                       trainable=True)
        
    def call(self, inputs):
        filter_small = self.filter_small / self.q_small

        # Input shape: [batch_size, height, width, channels]
        # Filter shape: [height, width, in_channels, out_channels]

        conv_small = tf.nn.conv2d(inputs, 
                                  tf.expand_dims(tf.expand_dims(filter_small, axis=-1), axis=-1), 
                                  strides=[1, 1, 1, 1], 
                                  padding='SAME')
        
        # conv_meddd = tf.nn.conv2d(inputs, filter_small, strides=[1, 1, 1, 1], padding='SAME')

        # outputs = tf.concat([conv_small, conv_meddd], axis=-1)
        return conv_small

In [ ]:
tmp_model = keras.Sequential([
    keras.layers.Input(shape=(256, 256, 3)),
    TSRM(),
    Flatten(),
    Dense(1, activation='sigmoid')
])

tmp_model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

In [40]:
tmp_history = tmp_model.fit(train_dataset_cdfv1, epochs=1, validation_data=val_dataset_cdfv1)

138/138 [==============================] - 21s 133ms/step - loss: 722.0818 - accuracy: 0.5884 - val_loss: 549.3903 - val_accuracy: 0.4255


In [34]:
tmp_kernel1 = np.array([[0, 0,  0, 0, 0],
                    [0, 0,  0, 0, 0],
                    [0, 1, -2, 1, 0],
                    [0, 0,  0, 0, 0],
                    [0, 0,  0, 0, 0]], dtype=float)

tmp_kernel2 = np.array([[0,  0,  0,  0, 0],
                    [0, -1,  2, -1, 0],
                    [0,  2, -4,  2, 0],
                    [0, -1,  2, -1, 0],
                    [0,  0,  0,  0, 0]], dtype=float)

tmp_kernel3 = np.array([[-1,  2,  -2,  2, -1],
                    [ 2, -6,   8, -6,  2],
                    [-2,  8, -12,  8, -2],
                    [ 2, -6,   8, -6,  2],
                    [-1,  2,  -2,  2, -1]], dtype=float)

tmp_fixed_kernals = [tmp_kernel1, tmp_kernel2, tmp_kernel3]
tmp_custom_layer = SRMLayer(filters=3, kernel_size=(5, 5), fixed_filters=tmp_fixed_kernals)

## Implementation